In [2]:
import numpy as np 
from sklearn.datasets import load_digits
import pandas as pd 

In [3]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [4]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression



In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test  = train_test_split(digits.data,digits.target,train_size  = 0.8)

logistic Regression 

In [7]:
lr = LogisticRegression()


In [8]:
print(get_score(lr,X_train,X_test,Y_train,Y_test))

0.9666666666666667


c:\phython 3.7\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


SVM model 


In [9]:
SVM_model = SVC()

In [10]:
print(get_score(SVM_model,X_train,X_test,Y_train,Y_test))

0.9888888888888889


In [11]:
rf = RandomForestClassifier(n_estimators  = 70)

In [12]:
print(get_score(rf,X_train,X_test,Y_train,Y_test))

0.9833333333333333


**KFold**

In [13]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [14]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


**use KFold for our digits example**

In [15]:
from sklearn.model_selection import StratifiedKFold

In [16]:
folds  = StratifiedKFold(n_splits= 3)
folds
data = np.array([1,2,3,4,5,6,7,8,9])
target = np.array([0, 1, 0, 1, 1, 0, 1, 0, 1])

In [17]:
for train_index,test_index in folds.split(data,target):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [51]:
logistic_reg_model = []
svm_model = []
rf_model = []
for TrainIndex,TestIndex in folds.split(digits.data,digits.target):
    train_x,train_y,test_x,test_y = digits.data[TrainIndex],digits.data[TestIndex],digits.target[TrainIndex],digits.target[TestIndex]
    logistic_reg_model.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),train_x,train_y,test_x,test_y))
    svm_model.append(get_score(SVC(C=10),train_x,train_y,test_x,test_y))
    rf_model.append(get_score(RandomForestClassifier(n_estimators=50),train_x,train_y,test_x,test_y))
    


In [52]:
logistic_reg_model

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [45]:
svm_model

[0.9682804674457429, 0.9799666110183639, 0.9732888146911519]

In [35]:
rf_model

[0.9348914858096828, 0.9398998330550918, 0.9215358931552587]

# Cross Val score function 

equivalent to previous for loop 

In [46]:
from sklearn.model_selection import cross_val_score

In [49]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv = 3)

array([0.89482471, 0.95325543, 0.90984975])

In [53]:
cross_val_score(SVC(),digits.data,digits.target,cv = 3)

array([0.96494157, 0.97996661, 0.96494157])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=3)

array([0.93489149, 0.94156928, 0.92153589])