In [1]:
import numpy as np 
from sklearn.datasets import load_iris
import pandas as pd 

In [2]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
from sklearn.model_selection import cross_val_score

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [7]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target)

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=7),iris.data,iris.target)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [22]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [24]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])